site_name: Rago Meditation Server
site_url: https://bytefield.github.io/meditacion_app_server/
repo_url: https://github.com/Bytefield/meditacion_app_server
repo_name: Bytefield/meditacion_app_server

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'Home.md'

nav:
  - Home: 'Home.md'
  - API Documentation:
    - 'API/Overview.md'
    - 'API/Authentication.md'
  - Architecture:
    - 'Architecture/Overview.md'
  - Development:
    - 'Development/Setup.md'
    - 'Development/Deployment.md'
  - Contributing:
    - 'Contributing/How-to-Contribute.md'
    - 'Contributing/Code-Style.md'
