name: Deploy Server Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material for MkDocs
        run: |
          pip install mkdocs-material mkdocs-redirects

      - name: Create docs directory if it doesn't exist
        run: mkdir -p docs

      - name: Build site
        run: mkdocs build --site-dir public

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
